FROM sonatype/nexus3

MAINTAINER lx

ENV TZ Asia/Shanghai

# set the timezone
# ENV TZ Asia/Shanghai

# USER root

# RUN rm /usr/share/zoneinfo/UTC && cp /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/UTC