FROM sonatype/nexus

MAINTAINER lx

# RUN sudo echo "Asia/Shanghai" > /etc/timezone && sudo dpkg-reconfigure -f noninteractive tzdata
# COPY timezone /etc/timezone
# RUN dpkg-reconfigure -f noninteractive tzdata

# RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY localtime /etc/localtime